### ISSUE TITLE
Opening Minecraft Launcher

### ISSUE THREAD

**Issue by Apacci** [KinderrKill/MinecraftLauncher#2]
Hey when i  click on paly, the launcher open me the minecraft launcher 
![Sans titre](https://user-images.githubusercontent.com/71091240/113342180-783d6400-932e-11eb-887d-26d136fdc328.png)

**Comment by pingusurmars** [comment]
it's normal it works like that

**Comment by KinderrKill** [comment]
Yep ! It's an installer not a launcher :)
